/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package universidad.vistas;

import universidad.entidades.Alumno;
import universidad.accesoADatos.AlumnoData;
import java.sql.*;
import java.time.LocalDate;
import java.time.ZoneId;
import javax.swing.JOptionPane;
import universidad.ValidacionDatos;

/**
 *
 * @author Lucas Cometto
 */
public class AlumnosVista extends javax.swing.JInternalFrame {// Para un DNI de 8 dígitos
   
    public AlumnosVista() {
    initComponents();
    jBguardar.setToolTipText("Actualiza los campos, primero debe BUSCAR un alumno");
    jBnuevo.setToolTipText("Crea un nuevo Alumno");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLalumno = new javax.swing.JLabel();
        jLdocumento = new javax.swing.JLabel();
        jLapellido = new javax.swing.JLabel();
        jLnombre = new javax.swing.JLabel();
        jLestado = new javax.swing.JLabel();
        jLfecha = new javax.swing.JLabel();
        jBnuevo = new javax.swing.JButton();
        jBeliminar = new javax.swing.JButton();
        jBguardar = new javax.swing.JButton();
        jBsalir = new javax.swing.JButton();
        jRadioEstado = new javax.swing.JRadioButton();
        jTdocumento = new javax.swing.JTextField();
        jTapellido = new javax.swing.JTextField();
        jTnombre = new javax.swing.JTextField();
        jDfecha = new com.toedter.calendar.JDateChooser();
        jBbuscar = new javax.swing.JButton();
        jCdadosBaja = new javax.swing.JCheckBox();

        setClosable(true);

        jLalumno.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLalumno.setText("Alumno");

        jLdocumento.setText("DNI:");

        jLapellido.setText("Apellido:");

        jLnombre.setText("Nombre:");

        jLestado.setText("Estado:");

        jLfecha.setText("Fecha nacimiento;");

        jBnuevo.setText("Nuevo");
        jBnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnuevoActionPerformed(evt);
            }
        });

        jBeliminar.setText("Eliminar");
        jBeliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBeliminarActionPerformed(evt);
            }
        });

        jBguardar.setText("Guardar");
        jBguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBguardarActionPerformed(evt);
            }
        });

        jBsalir.setText("Salir");
        jBsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsalirActionPerformed(evt);
            }
        });

        jRadioEstado.setText("Tildar para activo");

        jDfecha.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDfechaPropertyChange(evt);
            }
        });

        jBbuscar.setText("Buscar");
        jBbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBbuscarActionPerformed(evt);
            }
        });

        jCdadosBaja.setText("Buscar dados de baja");
        jCdadosBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCdadosBajaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLestado)
                            .addComponent(jLnombre))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioEstado)
                            .addComponent(jTapellido, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBnuevo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBeliminar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBguardar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBsalir))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLfecha)
                                    .addComponent(jLapellido, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(18, 18, 18)
                                .addComponent(jDfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(145, 145, 145)
                                        .addComponent(jLalumno)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLdocumento)
                                        .addGap(44, 44, 44)
                                        .addComponent(jTdocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                                        .addComponent(jBbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jCdadosBaja)))
                                .addGap(8, 8, 8)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLalumno)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLdocumento)
                    .addComponent(jTdocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBbuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCdadosBaja)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLapellido)
                    .addComponent(jTapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLnombre)
                    .addComponent(jTnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLestado)
                    .addComponent(jRadioEstado))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLfecha)
                    .addComponent(jDfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBnuevo)
                    .addComponent(jBeliminar)
                    .addComponent(jBguardar)
                    .addComponent(jBsalir))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jBeliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBeliminarActionPerformed
        // voy a intentar validar con expresiones regulares
      // voy a intentar validar con expresiones regulares
        String dniString = jTdocumento.getText();
        if (!ValidacionDatos.validarDNI(dniString)) {
        JOptionPane.showMessageDialog(this, "Ingrese un DNI válido (7 u 8 dígitos numéricos).");
        return;
        }       
        try {
            int dni = Integer.parseInt(dniString);
            AlumnoData ad = new AlumnoData();
            Alumno al = ad.buscarAlumnoPorDni(dni);
            jTdocumento.setText(String.valueOf(al.getDni()));
            jTapellido.setText(al.getApellido());
            jTnombre.setText(al.getNombre());
            jDfecha.setDate(Date.valueOf(al.getFechaNac()));
            jRadioEstado.setSelected(al.isActivo());
            int id = al.getIdAlumno();
            ad.eliminarAlumno(id);
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(this, "Ooops!");
        }
        limpiar();
    }//GEN-LAST:event_jBeliminarActionPerformed

    private void jBsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBsalirActionPerformed

    private void jBguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBguardarActionPerformed

        String dniString = jTdocumento.getText();
        String nombre = jTnombre.getText();
        String apellido = jTapellido.getText();
        boolean activo = jRadioEstado.isSelected();
        int dni;
        if (!ValidacionDatos.validarDNI(dniString)) {
            JOptionPane.showMessageDialog(this, "Ingrese un DNI válido (8 dígitos numéricos).");
            return;
        }

        if (!ValidacionDatos.validarNombre(nombre)) {
            JOptionPane.showMessageDialog(this, "Ingrese un nombre válido (solo letras y espacios).");
            return;
        }

        if (!ValidacionDatos.validarApellido(apellido)) {
            JOptionPane.showMessageDialog(this, "Ingrese un apellido válido (solo letras y espacios).");
            return;
        }LocalDate fechald;
        if (jDfecha.getDate() != null) {
            //   LocalDate fechald;
            dni = Integer.parseInt(dniString);
            fechald = jDfecha.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            AlumnoData ad = new AlumnoData();
            Alumno al = new Alumno(dni, apellido, nombre, fechald, activo);
            ad.modificarAlumno(al);
        }
        limpiar();
    }//GEN-LAST:event_jBguardarActionPerformed

    private void jDfechaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDfechaPropertyChange
        //      if (jDfecha.getDate()!= null){
        //    LocalDate fechald;
        //  fechald=jDfecha.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        //  }
    }//GEN-LAST:event_jDfechaPropertyChange

    private void jBnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnuevoActionPerformed
        // TODO add your handling code here:
        String dniString = jTdocumento.getText();
        String nombre = jTnombre.getText();
        String apellido = jTapellido.getText();
        boolean activo = jRadioEstado.isSelected();
        int dni;
        if (!ValidacionDatos.validarDNI(dniString)) {
            JOptionPane.showMessageDialog(this, "Ingrese un DNI válido (7 u 8 dígitos numéricos).");
            return;
        }
        if (!ValidacionDatos.validarApellido(apellido)) {
            JOptionPane.showMessageDialog(this, "Ingrese un apellido válido (solo letras y espacios).");
            return;
        }
        if (!ValidacionDatos.validarNombre(nombre)) {
            JOptionPane.showMessageDialog(this, "Ingrese un nombre válido (solo letras y espacios).");
            return;
        }

      
        try {

            dni = Integer.parseInt(dniString);

            // int dni;
            //  String nombre, apellido;
            //  boolean activo;
            //try {
            //    dni = Integer.parseInt(jTdocumento.getText());
            //    nombre = jTnombre.getText();
            //    apellido = jTapellido.getText();
            //    activo = jRadioEstado.isSelected();
            LocalDate fechald;
            if (jDfecha.getDate() != null) {//viene del jcalendar solo valido que no esté vacío
                //   LocalDate fechald;
                fechald = jDfecha.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
                AlumnoData ad = new AlumnoData();
                Alumno alumno = new Alumno(dni, apellido, nombre, fechald, activo);
                ad.guardarAlumno(alumno);

            } else {
                JOptionPane.showMessageDialog(this, "La fecha de nacimiento no puede estar vacía");
                return;
            }//necesito que lo llene
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Error! " + ex.toString());
        }
        limpiar();
    }//GEN-LAST:event_jBnuevoActionPerformed

    private void jBbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBbuscarActionPerformed
        String dniString = jTdocumento.getText();
        
       try {
            if (!ValidacionDatos.validarDNI(dniString)) {
            JOptionPane.showMessageDialog(this, "Ingrese un DNI válido (7 u 8 dígitos numéricos).");
            return;
        }
            int dni = Integer.parseInt(jTdocumento.getText());
            
            AlumnoData ad = new AlumnoData();
            Alumno al = null;
            if(jCdadosBaja.isSelected()){
                al = ad.buscarAlumnoDadoBajaPorDni(dni);
            }else{
                al = ad.buscarAlumnoPorDni(dni);
            }
            if (al != null){ // si no encontraba el alumno entraba en el catch
            jTdocumento.setText(String.valueOf(al.getDni()));
            jTapellido.setText(al.getApellido());
            jTnombre.setText(al.getNombre());
            jDfecha.setDate(Date.valueOf(al.getFechaNac()));
            jRadioEstado.setSelected(al.isActivo());
       }
       } catch (NullPointerException ex) {
           JOptionPane.showMessageDialog(this, "Algo no funcionó");
       }

    }//GEN-LAST:event_jBbuscarActionPerformed

    private void jCdadosBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCdadosBajaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCdadosBajaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBbuscar;
    private javax.swing.JButton jBeliminar;
    private javax.swing.JButton jBguardar;
    private javax.swing.JButton jBnuevo;
    private javax.swing.JButton jBsalir;
    private javax.swing.JCheckBox jCdadosBaja;
    private com.toedter.calendar.JDateChooser jDfecha;
    private javax.swing.JLabel jLalumno;
    private javax.swing.JLabel jLapellido;
    private javax.swing.JLabel jLdocumento;
    private javax.swing.JLabel jLestado;
    private javax.swing.JLabel jLfecha;
    private javax.swing.JLabel jLnombre;
    private javax.swing.JRadioButton jRadioEstado;
    private javax.swing.JTextField jTapellido;
    private javax.swing.JTextField jTdocumento;
    private javax.swing.JTextField jTnombre;
    // End of variables declaration//GEN-END:variables

    private void limpiar() {
        jTdocumento.setText("");
        jTapellido.setText("");
        jTnombre.setText("");
        jRadioEstado.setSelected(false);
        jDfecha.setDate(null);
    }

}
